apiVersion: v1
kind: Service
metadata:
  name: good-grocer-api-service
spec:
  selector:
    app: good-grocer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
