DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "communities";
DROP TABLE IF EXISTS "members";
DROP TABLE IF EXISTS "items";
DROP TABLE IF EXISTS "stores";
DROP TABLE IF EXISTS "requests";
DROP TABLE IF EXISTS "errands";