// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    hashed_password,
    full_name,
    phone_number,
    address_line_1,
    address_line_2,
    zip_code,
    city,
    state
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state
`

type CreateUserParams struct {
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashed_password"`
	FullName       string         `json:"full_name"`
	PhoneNumber    string         `json:"phone_number"`
	AddressLine1   string         `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	ZipCode        string         `json:"zip_code"`
	City           string         `json:"city"`
	State          string         `json:"state"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FullName,
		arg.PhoneNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.ZipCode,
		arg.City,
		arg.State,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.ZipCode,
		&i.City,
		&i.State,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.ZipCode,
		&i.City,
		&i.State,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.ZipCode,
		&i.City,
		&i.State,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state FROM users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.ZipCode,
		&i.City,
		&i.State,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state FROM users
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.FullName,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.ZipCode,
			&i.City,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = $2,
    hashed_password = $3,
    full_name = $4,
    phone_number = $5,
    address_line_1 = $6,
    address_line_2 = $7,
    zip_code = $8,
    city = $9,
    state = $10
WHERE id = $1
RETURNING id, email, hashed_password, full_name, phone_number, created_at, address_line_1, address_line_2, zip_code, city, state
`

type UpdateUserParams struct {
	ID             int64          `json:"id"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashed_password"`
	FullName       string         `json:"full_name"`
	PhoneNumber    string         `json:"phone_number"`
	AddressLine1   string         `json:"address_line_1"`
	AddressLine2   sql.NullString `json:"address_line_2"`
	ZipCode        string         `json:"zip_code"`
	City           string         `json:"city"`
	State          string         `json:"state"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.FullName,
		arg.PhoneNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.ZipCode,
		arg.City,
		arg.State,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.ZipCode,
		&i.City,
		&i.State,
	)
	return i, err
}
