name: Run unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-backend:
    name: Run backend unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: good_grocer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test

  test-frontend:
    name: Run frontend unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend/GoodGrocer
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --only=dev

      - name: Test
        run: npm test
